(module
 (type $FUNCSIG$iii (func (param i32 i32) (result i32)))
 (type $FUNCSIG$v (func))
 (table 3 3 anyfunc)
 (elem (i32.const 0) $__wasm_nullptr $add $mult)
 (memory $0 1)
 (export "memory" (memory $0))
 (export "add" (func $add))
 (export "mult" (func $mult))
 (export "main" (func $main))
 (func $add (; 0 ;) (type $FUNCSIG$iii) (param $0 i32) (param $1 i32) (result i32)
  (i32.add
   (get_local $1)
   (get_local $0)
  )
 )
 (func $mult (; 1 ;) (type $FUNCSIG$iii) (param $0 i32) (param $1 i32) (result i32)
  (i32.shl
   (get_local $0)
   (i32.const 1)
  )
 )
 (func $main (; 2 ;) (result i32)
  (call_indirect (type $FUNCSIG$iii)
   (i32.const 2)
   (i32.const 5)
   (select
    (i32.const 1)
    (i32.const 2)
    (i32.gt_s
     (call $add
      (i32.const 2)
      (i32.const 6)
     )
     (i32.const 4)
    )
   )
  )
 )
 (func $__wasm_nullptr (; 3 ;) (type $FUNCSIG$v)
  (unreachable)
 )
)
